### PR TITLE
Add pom.xml to enable Maven builds and release management

### PR DESCRIPTION
**Pull request by brk3**
Hi, so this should hopefully be all ready now.  With the pom.xml in place you can begin to build using maven or continue to use Ant.

Users can add android-query to their maven enabled projects with:

```
<dependency>
    <groupId>com.googlecode.android-query</groupId>
    <artifactId>android-query</artifactId>
    <version>0.24.3</version>
</dependency>
```

I'd recommend you add this info to the googlecode page.

In regards to future releases, if you would be interested in doing them you would need to create a Sonatype JIRA account as outlined at https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide , and then let me know so I can request your account gets added to the list of users authorised to stage/promote releases.

If you're not too bothered with learning the ins and outs of Maven right now (I wouldn't blame you!), I can continue to help out by pushing up releases whenever they're ready.

Any questions just let me know.

-Paul

### CODE REVIEW

**Comment by pietrocaselani** [comment]
+1!

**Comment by a-thomas** [comment]
+1 I'm the developer of [AndroidKickstartr](http://androidkickstartr.com/). I'm waiting for the availability of AndroidQuery on Maven central before adding it on AndroidKickstartR.

**Comment by tinyeeliu** [comment]
Merged. Will appreciate if someone can confirm that it's working. Thanks.

**Comment by adrien-aubel** [comment]
It's working fine with 0.24.3, but not working with latest version (0.25.10).

**Comment by brk3** [comment]
@adrien-aubel [0.25.9](http://search.maven.org/#search%7Cga%7C1%7Candroid-query) is the latest release I've published.

**Comment by mspapant** [comment]
Could you please also uploaded the auth / or full version to the repository?

Thank you!

**Comment by lassic** [comment]
:+1: on @mspapant request. thanks!

**Pull request merged**
